name: Release to firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6' # set your version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release
      - run: ls build/app/outputs/flutter-apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          groups: testers-for-chat-app
          file: build/app/outputs/flutter-apk/app-release.apk